# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "workflow-test" ]
  pull_request:
    branches: [ "workflow-test" ]

jobs:

  build:
    runs-on: self-hosted
    strategy:
      matrix:
        go-version: ['1.22']
        goos: [linux, windows, freebsd]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
          go-version: ${{ matrix.go-version }}
          
    - name: Test
      run: go test -v ./...

    - name: Build
      run: |
          mkdir -p ./dist/${{ matrix.goos }}_${{ matrix.goarch }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./dist/${{ matrix.goos }}_${{ matrix.goarch }}_${{ maxtrix.go-version }}/myapp

    - name: Upload binary artifact
      uses: actions/upload-artifact@v3
      with:
        name: file-mover-daemon-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.go-version }}
        path: ./dist/${{ matrix.goos }}_${{ matrix.goarch }}_${{ matrix.go-version }}/file-mover-daemon

