name: Build Release

on:
  release:
    types: [released]

permissions:
  contents: write

env:
  GO_VERSION: '1.22'

jobs:

  build and upload:
    runs-on: self-hosted
    strategy:
      matrix:
        goos: [linux, windows, freebsd]
        goarch: [amd64, arm64]

    steps:

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Test
      run: go test -v ./...

    - name: Build
      run: |
          mkdir -p ./dist/${{ matrix.goos }}_${{ matrix.goarch }}_${{ github.event.release.name }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./dist/${{ matrix.goos }}_${{ matrix.goarch }}_${{ github.event.release.name }}/file-mover-daemon cmd/main.go

    - name: Package the build
      run: |
        zip -r ./dist/file-mover-daemon-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.name }}.zip ./dist/${{ matrix.goos }}_${{ matrix.goarch }}_${{ github.event.release.name }}
        touch ./dist/conf.yml
        zip -r ./dist/file-mover-daemon-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.name }}.zip ./dist/conf.yml

    - name: Upload Release Artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/file-mover-daemon-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.name }}.zip
        asset_name: file-mover-daemon-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.name }}.zip
        asset_content_type: application/zip
