name: Build Release

on:
  release:
    types: [released]

permissions:
  contents: write

env:
  GO_VERSION: '1.22'

jobs:

  build:
    runs-on: self-hosted
    strategy:
      matrix:
        goos: [linux, windows, freebsd]
        goarch: [amd64, arm64]

    steps:

    - name: Set name variable
      run: echo "name=${{ matrix.goos }}_${{ matrix.goarch }}_${{ github.event.release.name }}" >> $GITHUB_ENV

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Test
      run: go test -v ./...

    - name: Build
      run: |
          mkdir -p ./$name/conf
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./$name/file-mover-daemon cmd/main.go

    - name: Package the build
      run: |
        zip -r ./file-mover-daemon-$name.zip ./$name/file-mover-daemon
        echo "# Edit me!" > ./$name/conf/conf.yml
        echo '# Example file @ https://github.com/NebN/file-mover-daemon' >> ./$name/conf/conf.yml
        zip -r ./file-mover-daemon-$name.zip ./$name/conf/conf.yml

    - name: Upload Release Artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./file-mover-daemon-$name.zip
        asset_name: file-mover-daemon-$name.zip
        asset_content_type: application/zip
