name: Build Release

on:
  release:
    types: [released]

permissions:
  contents: write

env:
  GO_VERSION: '1.22'

jobs:

  build:
    runs-on: self-hosted
    strategy:
      matrix:
        goos: [linux, windows, freebsd]
        goarch: [amd64, arm64]

    steps:

    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Test
      run: go test -v ./...

    - name: Build
      run: |
          mkdir -p ./dist/${{ matrix.goos }}_${{ matrix.goarch }}_${{ github.event.release.name }}
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./dist/${{ matrix.goos }}_${{ matrix.goarch }}_${{ github.event.release.name }}/file-mover-daemon cmd/main.go

    - name: Install zip (Linux)
      if: matrix.goos != 'windows'
      run: sudo apt-get install -y zip

    # Package the folder (zip for Windows, tar.gz for others)
    - name: Package the build (Windows)
      if: matrix.goos == 'windows'
      run: |
        zip -r ./dist/file-mover-daemon-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.name }}.zip ./dist/${{ matrix.goos }}_${{ matrix.goarch }}_${{ github.event.release.name }}

    - name: Package the build (Linux/FreeBSD)
      if: matrix.goos != 'windows'
      run: |
        tar -czvf ./dist/file-mover-daemon-${{ matrix.goos }}-${{ matrix.goarch }}_${{ github.event.release.name }}.tar.gz -C ./dist/${{ matrix.goos }}_${{ matrix.goarch }}_${{ github.event.release.name }} .

    - name: Upload Release Artifacts (Linux/FreeBSD)
      if: matrix.goos != 'windows'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/file-mover-daemon-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.name }}.tar.gz
        asset_name: file-mover-daemon-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.name }}.tar.gz
        asset_content_type: application/gzip
        
    - name: Upload Release Artifacts (Windows)
      if: matrix.goos == 'windows'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/file-mover-daemon-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.name }}.zip
        asset_name: file-mover-daemon-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.event.release.name }}.zip
        asset_content_type: application/zip
